name: Validate MD Files in Shows Folder

on:
  push:
    paths:
      - 'shows/**'

jobs:
  check-md-extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check for MD file extensions in ./shows folder
        run: |
          for file in $(git diff --name-only HEAD~1 -- './shows/*'); do
            if [[ ! "$file" =~ \.md$ ]]; then
              echo "::error ::File $file does not have a .md extension."
              exit 1
            fi
          done
