name: Validate MD Files in Shows Folder

on:
  push:
    paths:
      - 'shows/**'

jobs:
  validate-md-extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate all .md files in ./shows folder
        run: |
          # List all files in the ./shows directory
          files=$(find ./shows -type f)
          error=0
          for file in $files; do
            if [[ ! "$file" =~ \.md$ ]]; then
              echo "::error file=$file::File does not have a .md extension."
              error=1
            fi
          done

          if [ "$error" -ne 0 ]; then
            exit 1
          fi
